influxdbservice:
  communication:
    messaging:
      rabbit:
        queue: q.influxdb_service
    influx:
      url: http://localhost:8086
      username: admin
      password: admin

logging:
  pattern:
    console: "%clr(%d{\"yyyy-MM-dd'T'HH:mm:ss,SSSXXX\", UTC}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr([%X{correlationId:-}]){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{\"yyyy-MM-dd'T'HH:mm:ss,SSSXXX\", UTC} ${LOG_LEVEL_PATTERN:%5p} ${PID: } --- [%t] [%X{correlationId:-}] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: logs/logreposit-api.log

server:
    port: "${port:8080}"
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

spring:
  jackson:
    #date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  resources:
    add-mappings: false
